version: '3.8'

services:
  # Nginx 反向代理和SSL终止
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx:ro
      - ./nginx/html:/usr/share/nginx/html
      - ./certbot/data:/etc/letsencrypt:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - frps
    restart: unless-stopped
    networks:
      - app-network

  # FRPS 服务器
  frps:
    image: snowdreamtech/frps:latest
    container_name: frps-server
    ports:
      - "7000:7000"       # FRPS 主端口
      - "7001:7001"       # Dashboard 端口
    volumes:
      - ./frps/config:/etc/frp
      - ./frps/custom_errors:/etc/frp/custom_errors
      - ./logs/frps:/var/log/frps
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16